#!/bin/bash
#for github:git add/git commit -m/git push
#By GaoZQ

git status;
read -p "input commit message:" M
echo "commit:(y/n)"
read tmp
if [ tmp=="y" ];then
	git add -A;
	git commit -m "$M";
	git push origin master;
fi
